# syntax=docker/dockerfile:1

FROM node:24.15.0-alpine3.23 AS build
ARG VERSION=dev
ARG REVISION=unknown
WORKDIR /web

COPY web/package*.json ./
RUN npm ci

COPY web/ ./
RUN npm run build

FROM nginx:1.30.0-alpine3.23
ARG VERSION=dev
ARG REVISION=unknown
ARG SOURCE_URL=https://github.com/bitofbytes-io/anthology
WORKDIR /usr/share/nginx/html

COPY Docker/ui/nginx.conf /etc/nginx/conf.d/default.conf
COPY Docker/ui/entrypoint.sh /entrypoint.sh

COPY --from=build /web/dist/web/browser ./

LABEL org.opencontainers.image.source="${SOURCE_URL}" \
      org.opencontainers.image.revision="${REVISION}" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.title="anthology-ui" \
      org.opencontainers.image.description="Anthology UI service"

RUN set -eux; \
    if [ -f assets/runtime-config.js ]; then \
        mv assets/runtime-config.js assets/runtime-config.default.js; \
    fi; \
    chmod +x /entrypoint.sh

ENV NG_APP_API_URL=

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
